### PR TITLE
Removed MessageRemover functionality

### LINKED ISSUE #29: remove bot message self-deletion feature
The chatbot self-deleting its messages has been requested to be removed by users.

### PR DESCRIPTION
**Pull request by JoshCode**
Remove self-deleting responses.
Only self-deleting response left over, `!help`, increased by 600% longer display time.

Fixes #29

### CODE REVIEW

**Comment by dasbif** [comment]
> Only self-deleting response left over, !help, increased by 600% longer display time.

@JoshCode  `!help` should not still self delete at all, even with longer display time - this is the most important command to permanently NOT self-delete, so users can know how the chatbot works.  `!help` is a command specifically requested by our users to be permanent.

**Comment by JoshCode** [comment]
@dasbif !help is the most spam-prone command. It's even going to be expanded with subcommand listings, making it a very large response. I'm keeping MessageRemover active for that one.

**Comment by dasbif** [comment]
This is why I requested an external documentation page months ago, so the !help command can link to that rather than trying to display all commands within the chat.

!help was SPECIFICALLY requested by our users to not self-delete.  What about functionality where, on calling !help, the bot would message the full documentation to the user, and put a message in the chat channel "I have messaged you the help documentation", if that would be easier to implement than making an external page?

Making !help self delete increases spam.  It does not decrease it - because if it remains in the chatlog, users can see, use, and read it without having to call it again for themselves.  It is very important not to self-delete that message.

**Comment by JoshCode** [comment]
I'll remove the self destruct once the documentation page is up then

**Pull request merged**
