### PR TITLE
Fixes #53

### LINKED ISSUE #53: !roll stats doesn't work, appears to have outputs off by a line
!roll stats doesn't work correctly, appears to have outputs off by a line

Dasbif - Today at 11:53 AM
!roll stats
GilmoreBOT - Today at 11:53 AM
null = 17
4d6kh3 (5, 6, 6, 1) = 10
4d6kh3 (3, 3, 4, 3) = 12
4d6kh3 (5, 1, 5, 2) = 10
4d6kh3 (3, 1, 1, 6) = 12
4d6kh3 (2, 6, 2, 4) = 9

### PR DESCRIPTION
**Pull request by Elthan**
It tried to get breakdown before rolling, fixed this.

### CODE REVIEW

**Review by JoshCode — APPROVED** [review]
I thought I already merged this 🤦‍♂️

**Comment by JoshCode** [comment]
Thought I merged this already.
Can you squash your commits and edit the branch to be pulled into to 'dev'?

**Comment by Elthan** [comment]
Wasn't able to squash the commits (never done it before), but I believe you should have the option to squash and confirm pull?

**Comment by JoshCode** [comment]
Oh hey, that's new I believe

**Pull request merged**
